config-version: 2

name: 'salesforce_source'
version: '0.0.1'

models:
    salesforce_source:
        materialized: table

vars:
    salesforce_source:
        account: "{{ source('salesforce', 'account') }}" 
        opportunity: "{{ source('salesforce', 'opportunity') }}" 
        user: "{{ source('salesforce', 'user') }}"
        user_role: "{{ source('salesforce', 'user_role') }}"    