version: 2

models:

  - name: stg_salesforce_account
    columns:
      - name: account_id
        tests: 
          - not_null
          - unique

  - name: stg_salesforce_opportunity
    columns:
      - name: opportunity_id
        tests: 
          - not_null
          - unique

  - name: stg_salesforce_user
    columns:
      - name: user_id
        tests: 
          - not_null
          - unique

  - name: stg_salesforce_user_role
    columns:
      - name: user_role_id
        tests: 
          - not_null
          - unique
